const fakeProfile = {
  name: 'Loris',
  age: 49,
  maladie: 'Hypertension',
  diagnostic: '1 an',
  symptomes: ['Céphalées', 'fatigue'],
  poids: '95 kg',
  taille: '1m78',
  traitements: 'Antihypertenseur, marche quotidienne',
  suivi: ['Cardiologue', 'Médecin généraliste', 'Infirmier'],
  contexte: 'Surpoids, fatigue chronique, fumeur régulier, alimentation déséquilibrée',
  tech: 'Withings BPM Pro',
  motivation: "Début d'acceptation du diagnostic, motivé par l'entourage médical et un événement marquant.",
  heures: ['08:00', '12:00', '19:00'],
  notifications: true,
  cgu: true,
  monthData: [
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-02-27", fatigue: "modéré", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 2, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-02-28", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: true, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-02-29", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-01", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-02", fatigue: "léger", gonflements: "aucun", palpitations: "légère", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-03", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: false, stress_event: true, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-04", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-05", fatigue: "modéré", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-06", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-07", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: true, stress_event: true, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-08", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-09", fatigue: "modéré", gonflements: "aucun", palpitations: "légère", traitement_suivi: false, stress_event: true, sommeil: "moyen", activite_physique: 2, alcool_verres: 1, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-10", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-11", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-12", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-13", fatigue: "modéré", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-14", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-15", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: false, stress_event: true, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-16", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-17", fatigue: "modéré", gonflements: "aucun", palpitations: "légère", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-18", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-19", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-20", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-21", fatigue: "modéré", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-22", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-23", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: false, stress_event: true, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-24", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-25", fatigue: "modéré", gonflements: "aucun", palpitations: "légère", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-26", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2024-03-27", fatigue: "modéré", gonflements: "léger", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: false }
  ]
};
export default fakeProfile; 