const fakeProfile = {
  name: 'Loris',
  age: 49,
  maladie: 'Hypertension',
  diagnostic: '1 an',
  symptomes: ['Céphalées', 'fatigue'],
  poids: '95 kg',
  taille: '1m78',
  traitements: 'Antihypertenseur, marche quotidienne',
  suivi: ['Cardiologue', 'Médecin généraliste', 'Infirmier'],
  contexte: 'Surpoids léger, motivation élevée, arrêt du tabac récent, alimentation en amélioration',
  tech: 'Withings BPM Pro',
  motivation: "Début d'acceptation du diagnostic, motivé par l'entourage médical et un événement marquant.",
  heures: ['08:00', '12:00', '19:00'],
  notifications: true,
  cgu: true,
  monthData: [
    // Early data (before app usage) - showing poor health
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-01-15", fatigue: "sévère", gonflements: "modéré", palpitations: "fréquentes", traitement_suivi: false, stress_event: true, sommeil: "mauvais", activite_physique: 1, alcool_verres: 3, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-01-20", fatigue: "sévère", gonflements: "léger", palpitations: "légère", traitement_suivi: false, stress_event: true, sommeil: "mauvais", activite_physique: 1, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-01-25", fatigue: "modéré", gonflements: "modéré", palpitations: "fréquentes", traitement_suivi: false, stress_event: true, sommeil: "moyen", activite_physique: 1, alcool_verres: 4, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-01-30", fatigue: "sévère", gonflements: "léger", palpitations: "légère", traitement_suivi: false, stress_event: true, sommeil: "mauvais", activite_physique: 1, alcool_verres: 3, hydratation_ok: false, sel_haute_conso: true },
    
    // Transition period (starting to use app) - mixed results
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-02-05", fatigue: "modéré", gonflements: "léger", palpitations: "légère", traitement_suivi: true, stress_event: true, sommeil: "moyen", activite_physique: 2, alcool_verres: 2, hydratation_ok: true, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-02-10", fatigue: "modéré", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "moyen", activite_physique: 2, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-02-15", fatigue: "modéré", gonflements: "léger", palpitations: "légère", traitement_suivi: true, stress_event: true, sommeil: "moyen", activite_physique: 2, alcool_verres: 2, hydratation_ok: false, sel_haute_conso: true },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-02-20", fatigue: "modéré", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    
    // Recent data (current month) - showing improvement
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-02-27", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-02-28", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-01", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-02", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-03", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 1, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-04", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-05", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-06", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-07", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-08", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-09", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-10", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-11", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-12", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-13", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-14", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-15", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-16", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-17", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-18", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-19", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-20", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-21", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-22", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-23", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-24", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-25", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-26", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 4, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false },
    { user_id: "1e8e1b2c-1234-4a5b-8cde-123456789abc", date: "2025-03-27", fatigue: "léger", gonflements: "aucun", palpitations: "aucune", traitement_suivi: true, stress_event: false, sommeil: "bon", activite_physique: 3, alcool_verres: 0, hydratation_ok: true, sel_haute_conso: false }
  ]
};
export default fakeProfile; 